### ISSUE TITLE
Flume 1.8.0

### ISSUE THREAD

**Issue by michaldul** [mrwilson/docker-flume#9]
Hello @mrwilson,

would you consider PR with support of Flume 1.8.0?

//edit: it would not be as easy as migration to 1.7 as, at least for me, getting JRE from Oracle's servers does not work anymore.

Cheers,

**Comment by mrwilson** [comment]
Hi!

Thanks for this, I've bumped Flume to 1.8.0 and updated the version of the JRE too.

**Comment by michaldul** [comment]
Thank you @mrwilson. Works like a charm.
